name: Python testing

on: [push]

jobs:
  build:
    runs-on: [advent-runners]
    # strategy:
    #   matrix:
    #     year:
    #       - 2015
    #       - 2017
    #       - 2018
    #       - 2020
    #       - 2021
    #       - 2022

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Unit tests
        # run: |
        #   poetry run pytest tests/test_${{ matrix.year }}*
        run: |
          poetry run pytest
